// import './js/add-movie-list.js';
import './sass/main.scss';
import './js/modal';
import './js/contributors';
import './js/footer-animation';
import './js/spinner';
import './js/apiService';
import './js/gallery';
import './js/pagination';
import './js/my-library-btn';
import './js/navigation';
